from tkinter import *
from tkinter import messagebox
a=Tk()
var=IntVar()
checkvar1=IntVar()
checkvar2=IntVar()
checkvar3=IntVar()
def sel():
    selection='you selected the option'+ str(var.get())
    label.config(text=selection)
def yoo():
    e=Tk()
    e.geometry("800x800")
    l6=Label(e, text="You are done Thanks for applying")
    l6.grid(row=0,column=7)
def done():
    d=Tk()
    d.geometry("800x800")
    l4=Label(d, text="Select language")
    l4.grid(row=0,column=0,padx=20,pady=30)
    r2=Radiobutton(d, text='python',variable=var,value=1,command=sel)
    r2.grid(row=0, column=1)
    r3=Radiobutton(d, text='HTML',variable=var,value=2,command=sel)
    r3.grid(row=0, column=2)
    r4=Radiobutton(d, text='C',variable=var,value=3,command=sel)
    r4.grid(row=0, column=3)
    r5=Radiobutton(d, text='C++',variable=var,value=4,command=sel)
    r5.grid(row=0, column=4)
    b5=Button(d,text="Apply",command=yoo)
    b5.grid(row=1,column=2,padx=20,pady=30)
    b7=Button(d,text="Exit",command=processcancel)
    b7.grid(row=1,column=4,padx=20,pady=30)
    label=Label(d)
    label.grid(row=7,column=4)
def apply3():
    g=Tk()
    g.geometry("800x800")
    l4=Label(g, text="Select post")
    l4.grid(row=0,column=0,padx=20,pady=30)
    l5=Label(g, text="Assistant professor (salary:100000,Collage:Anna University,Qualification:Phd holder in computer science)")
    l5.grid(row=1,column=0,padx=20,pady=30)
    b3=Button(g,text="Next",command=processok)
    b3.grid(row=2,column=0,padx=20,pady=30)
    l6=Label(g, text="professor (salary:65000,Collage:Anna University,Qualification:Btech holder in computer science with atleat 80% marks)")
    l6.grid(row=3,column=0,padx=20,pady=30)
    b3=Button(g,text="Next",command=processok)
    b3.grid(row=4,column=0,padx=20,pady=30)
    l7=Label(g, text="Clerk (salary:35000,Collage:Anna University,Qualification:Passed 12th with atleat 80% marks)")
    l7.grid(row=5,column=0,padx=20,pady=30)
    b4=Button(g,text="Next",command=processok)
    b4.grid(row=6,column=0,padx=20,pady=30)
    b5=Button(g,text="Exit",command=processcancel)
    b5.grid(row=7,column=4,padx=20,pady=30)
def apply2():
    f=Tk()
    f.geometry("900x800")
    l4=Label(f, text="Select post")
    l4.grid(row=0,column=0,padx=20,pady=30)
    l5=Label(f, text="Assistant professor (salary:100000,Collage:Delhi Technological University,Qualification:Phd holder in computer science)")
    l5.grid(row=1,column=0,padx=20,pady=30)
    b3=Button(f,text="Next",command=processok)
    b3.grid(row=2,column=0,padx=20,pady=30)
    l6=Label(f, text="professor (salary:65000,Collage:Delhi Technological University,Qualification:Btech holder in computer science with atleat 80% marks)")
    l6.grid(row=3,column=0,padx=20,pady=30)
    b3=Button(f,text="Next",command=processok)
    b3.grid(row=4,column=0,padx=20,pady=30)
    l7=Label(f, text="Clerk (salary:35000,Collage:Delhi Technological University,Qualification:Passed 12th with atleat 80% marks)")
    l7.grid(row=5,column=0,padx=20,pady=30)
    b4=Button(f,text="Next",command=processok)
    b4.grid(row=6,column=0,padx=20,pady=30)
    b5=Button(f,text="Exit",command=processcancel)
    b5.grid(row=7,column=4,padx=20,pady=30)
def apply():
    c=Tk()
    c.geometry("800x800")
    l4=Label(c, text="Select post")
    l4.grid(row=0,column=0,padx=20,pady=30)
    l5=Label(c, text="Assistant professor (salary:100000,Collage:LPU,Qualification:Phd holder in computer science)")
    l5.grid(row=1,column=0,padx=20,pady=30)
    b3=Button(c,text="Next",command=processok)
    b3.grid(row=2,column=0,padx=20,pady=30)
    l6=Label(c, text="professor (salary:65000,Collage:LPU,Qualification:Btech holder in computer science with atleat 80% marks)")
    l6.grid(row=3,column=0,padx=20,pady=30)
    b3=Button(c,text="Next",command=processok)
    b3.grid(row=4,column=0,padx=20,pady=30)
    l7=Label(c, text="Clerk (salary:35000,Collage:LPU,Qualification:Passed 12th with atleat 80% marks)")
    l7.grid(row=5,column=0,padx=20,pady=30)
    b4=Button(c,text="Next",command=processok)
    b4.grid(row=6,column=0,padx=20,pady=30)
    b5=Button(c,text="Exit",command=processcancel)
    b5.grid(row=7,column=4,padx=20,pady=30)
def processok():
    top=Tk()
    top.geometry("800x800")
    l8=Label(top, text="Select field")
    l8.grid(row=0,column=0,padx=20,pady=30)
    l9=Label(top, text="Computer Science")
    l9.grid(row=1,column=0,padx=20,pady=30)
    b1=Button(top,text="Next",command=done)
    b1.grid(row=2,column=3,padx=20,pady=30)
    l10=Label(top, text="Mechanical")
    l10.grid(row=3,column=0,padx=20,pady=30)
    b1=Button(top,text="Apply",command=yoo)
    b1.grid(row=4,column=3,padx=20,pady=30)
    l11=Label(top, text='Civil')
    l11.grid(row=5,column=0,padx=20,pady=30)
    b1=Button(top,text="Apply",command=yoo)
    b1.grid(row=6,column=3,padx=20,pady=30)
    b2=Button(top,text="Exit",command=processcancel)
    b2.grid(row=7,column=5,padx=20,pady=30)
    label=Label(top)
    label.grid(row=7,column=4)
def processcancel():
    b=Tk()
    b.geometry("800x800")
    l3=Label(b, text="Thank you for using our window")
    l3.grid(row=0,column=3)
a.title("Find job")
a.geometry("800x800")
l2=Label(a, text="Select location")
l2.grid(row=0,column=0,padx=20,pady=30)
l3=Label(a, text='Jalandhar')
l3.grid(row=1,column=0,padx=20,pady=30)
b1=Button(a,text="Next",command=apply)
b1.grid(row=2,column=3,padx=20,pady=30)
l4=Label(a, text='Delhi')
l4.grid(row=3,column=0,padx=20,pady=30)
b1=Button(a,text="Next",command=apply2)
b1.grid(row=4,column=3,padx=20,pady=30)
l5=Label(a, text='Chennai')
l5.grid(row=5,column=0,padx=20,pady=30)
b1=Button(a,text="Next",command=apply3)
b1.grid(row=6,column=3,padx=20,pady=30)
b2=Button(a,text="Exit",command=processcancel)
b2.grid(row=7,column=4,padx=20,pady=30)
label=Label(a)
label.grid(row=7,column=4)
a.mainloop()

